/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Fraytline "Signal Field" tokens (design.md §3) — <alpha-value> enabled so
        // Tailwind /opacity modifiers work (CSS vars below remain for direct var() usage)
        canvas: 'rgb(14 13 11 / <alpha-value>)',
        'surface-1': 'rgb(22 20 15 / <alpha-value>)',
        'surface-2': 'rgb(29 26 20 / <alpha-value>)',
        'surface-3': 'rgb(38 34 25 / <alpha-value>)',
        'line-hairline': 'var(--line-hairline)',
        'line-strong': 'var(--line-strong)',
        'text-1': 'rgb(242 237 227 / <alpha-value>)',
        'text-2': 'rgb(168 159 142 / <alpha-value>)',
        'text-3': 'rgb(110 103 90 / <alpha-value>)',
        ember: 'rgb(232 145 45 / <alpha-value>)',
        'ember-hi': 'rgb(245 169 75 / <alpha-value>)',
        'ember-dim': 'var(--ember-dim)',
        teal: 'rgb(47 211 190 / <alpha-value>)',
        'teal-dim': 'var(--teal-dim)',
        warn: 'rgb(240 180 41 / <alpha-value>)',
        danger: 'rgb(227 93 91 / <alpha-value>)',
        ok: 'rgb(76 195 138 / <alpha-value>)',
        quote: 'rgb(143 184 216 / <alpha-value>)',
        // shadcn/ui compat
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive) / <alpha-value>)", foreground: "hsl(var(--destructive-foreground) / <alpha-value>)" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-xl': ['56px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '600' }],
        display: ['40px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        h1: ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['20px', { lineHeight: '26px', letterSpacing: '-0.02em', fontWeight: '600' }],
        h3: ['16px', { lineHeight: '22px', fontWeight: '500' }],
        body: ['14px', { lineHeight: '20px' }],
        small: ['13px', { lineHeight: '18px' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        micro: ['11px', { lineHeight: '15px', fontWeight: '600', letterSpacing: '0.09em' }],
        data: ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'data-lg': ['24px', { lineHeight: '28px', fontWeight: '600' }],
      },
      borderRadius: {
        chip: '6px',
        card: '10px',
        panel: '14px',
        modal: '20px',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        'glow-ember': '0 0 24px rgba(232,145,45,0.25)',
        'glow-teal': '0 0 24px rgba(47,211,190,0.22)',
        'glow-danger': '0 0 20px rgba(227,93,91,0.28)',
        modal: '0 24px 80px rgba(0,0,0,0.55)',
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        standard: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "caret-blink": { "0%,70%,100%": { opacity: "1" }, "20%,50%": { opacity: "0" } },
        "pulse-dot": { "0%,100%": { opacity: "1", transform: "scale(1)" }, "50%": { opacity: "0.35", transform: "scale(0.8)" } },
        breathe: { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.85" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "border-rotate": { to: { transform: "rotate(360deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-dot": "pulse-dot 1.6s ease-in-out infinite",
        "pulse-dot-slow": "pulse-dot 1.8s ease-in-out infinite",
        breathe: "breathe 4s ease-in-out infinite",
        shimmer: "shimmer 1.6s linear infinite",
        "border-rotate": "border-rotate 8s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
